### ISSUE TITLE
Runtime build on tag `polkadot-v0.9.16` fails

### ISSUE THREAD

**Issue by F3Joule** [substrate-developer-hub/substrate-parachain-template#95]
Running `cargo +nightly-2021-12-01 build --release --features runtime-benchmarks` fails (doesn't depend on toolchain version actually).

Output logs:
```sh
error: `PolkadotXcm` does not have the std feature enabled, this will cause the `pallet_xcm::GenesisConfig` type to be undefined.
   --> runtime/src/lib.rs:596:1
    |
596 | / construct_runtime!(
597 | |     pub enum Runtime where
598 | |         Block = Block,
599 | |         NodeBlock = opaque::Block,
...   |
629 | |     }
630 | | );
    | |_^
    |
    = note: this error originates in the macro `pallet_xcm::__substrate_genesis_config_check::is_std_enabled_for_genesis` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0412]: cannot find type `GenesisConfig` in crate `pallet_xcm`
   --> runtime/src/lib.rs:596:1
    |
596 | / construct_runtime!(
597 | |     pub enum Runtime where
598 | |         Block = Block,
599 | |         NodeBlock = opaque::Block,
...   |
629 | |     }
630 | | );
    | |_^ not found in `pallet_xcm`
    |
    = note: this error originates in the macro `construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
    |
9   | use cumulus_pallet_aura_ext::GenesisConfig;
    |
9   | use cumulus_pallet_parachain_system::GenesisConfig;
    |
9   | use frame_system::GenesisConfig;
    |
9   | use pallet_aura::GenesisConfig;
    |
      and 8 other candidates

error[E0405]: cannot find trait `AccountNonceApi` in crate `frame_system_rpc_runtime_api`
   --> runtime/src/lib.rs:727:37
    |
727 |     impl frame_system_rpc_runtime_api::AccountNonceApi<Block, AccountId, Index> for Runtime {
    |                                        ^^^^^^^^^^^^^^^ not found in `frame_system_rpc_runtime_api`
    |
help: consider importing this trait
    |
9   | use frame_system_rpc_runtime_api::runtime_decl_for_AccountNonceApi::AccountNonceApi;
    |

error[E0425]: cannot find function `account_nonce_call_api_at` in module `frame_system_rpc_runtime_api::runtime_decl_for_AccountNonceApi`
   --> runtime/src/lib.rs:647:1
    |
647 | / impl_runtime_apis! {
648 | |     impl sp_consensus_aura::AuraApi<Block, AuraId> for Runtime {
649 | |         fn slot_duration() -> sp_consensus_aura::SlotDuration {
650 | |             sp_consensus_aura::SlotDuration::from_millis(Aura::slot_duration())
...   |
816 | |     }
817 | | }
    | |_^ not found in `frame_system_rpc_runtime_api::runtime_decl_for_AccountNonceApi`
    |
    = note: this error originates in the macro `impl_runtime_apis` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0425]: cannot find function `account_nonce_native_call_generator` in module `frame_system_rpc_runtime_api::runtime_decl_for_AccountNonceApi`
   --> runtime/src/lib.rs:647:1
    |
647 | / impl_runtime_apis! {
648 | |     impl sp_consensus_aura::AuraApi<Block, AuraId> for Runtime {
649 | |         fn slot_duration() -> sp_consensus_aura::SlotDuration {
650 | |             sp_consensus_aura::SlotDuration::from_millis(Aura::slot_duration())
...   |
816 | |     }
817 | | }
    | |_^ not found in `frame_system_rpc_runtime_api::runtime_decl_for_AccountNonceApi`
    |
    = note: this error originates in the macro `impl_runtime_apis` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by F3Joule** [comment]
Fixed by 4bdc77a13a36fa261010aca4a6ae147d8bee6630
